services:
  quala-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=quala
      - PGDATA=/data/postgres-quala
    volumes:
      - postgres-quala:/data/postgres-quala

volumes:
  postgres-quala:
